apiVersion: v1
kind: Namespace
metadata:
  name: xclone
  labels:
    app.kubernetes.io/part-of: xclone-demo
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
