apiVersion: v1
kind: ServiceAccount
metadata:
  name: xclone-backend
  namespace: xclone
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<aws-account-id>:role/xclone-demo-backend-secrets-read
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xclone-frontend
  namespace: xclone
