apiVersion: v1
kind: Service
metadata:
  name: xclone-backend-operator-tailnet
  namespace: xclone
  labels:
    app.kubernetes.io/name: xclone-backend
    app.kubernetes.io/component: operator-tailnet
  annotations:
    tailscale.com/tags: "tag:k8s"
    tailscale.com/hostname: xclone-backend-operator-tailnet
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: xclone-backend
  ports:
    - name: http
      port: 8000
      targetPort: http
