apiVersion: v1
kind: Namespace
metadata:
  name: xclone
  labels:
    app.kubernetes.io/part-of: x-clone-demo
    app.kubernetes.io/managed-by: flux
---
apiVersion: v1
kind: Service
metadata:
  name: xclone-frontend
  namespace: xclone
  labels:
    app.kubernetes.io/name: xclone-frontend
    app.kubernetes.io/part-of: x-clone-demo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: xclone-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: xclone-backend-public-read
  namespace: xclone
  labels:
    app.kubernetes.io/name: xclone-backend
    app.kubernetes.io/component: public-read-edge
    app.kubernetes.io/part-of: x-clone-demo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: xclone-backend
  ports:
    - name: http
      port: 8000
      targetPort: http
