apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: xclone-platform-policies
  namespace: flux-system
spec:
  dependsOn:
    - name: xclone-platform-controllers
  interval: 10m
  path: ./deploy/gitops/platform/policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: xclone-gitops
  timeout: 5m
  wait: true
